name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
      
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install requirements.txt
      run: |
        pip install -r requirements.txt

    - name: Install sportypy
      run: |
        pip install .

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest --cov-config=.coveragerc

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2