name: Test sportypy and 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test sportypy
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install pytest, pytest-cov, and coverage
      run: python -m pip install pytest pytest-cov coverage

    - name: Install sportypy
      run: python -m pip install .

    - name: Run tests and collect coverage
      run: pytest --cov-config=.coveragerc --cov-report=xml

    - name: Upload coverage reports to codecov.io
      uses: codecov/codecov-action@v3